const ProductQuantityTypes={
    ADD_PRODUCT_QUANTITY:"ADD_PRODUCT_QUANTITY",
    REMOVE_PRODUCT_QUANTITY:"REMOVE_PRODUCT_QUANTITY",
    UPDATE_INITIAL_PRODUCT_QUANTITY:"UPDATE_INITIAL_PRODUCT_QUANTITY",
}

export default ProductQuantityTypes;