const CartTypes={
    ADD_PRODUCT_TO_CART_START:"ADD_PRODUCT_TO_CART_START",
    ADD_PRODUCT_TO_CART_SUCCESS:"ADD_PRODUCT_TO_CART_SUCCESS",
    ADD_PRODUCT_TO_CART_FAIL:"ADD_PRODUCT_TO_CART_FAIL",
    SUBTRACT_PRODUCT_FROM_CART_START:"SUBTRACT_PRODUCT_FROM_CART_START",
    SUBTACT_PRODUCT_FROM_CART_SUCCESS:"SUBTACT_PRODUCT_FROM_CART_SUCCESS",
    SUBTACT_PRODUCT_FROM_CART_FAIL:"SUBTACT_PRODUCT_FROM_CART_FAIL",
    REMOVE_ITEM_FROM_CART_START:"REMOVE_ITEM_FROM_CART_START",
    REMOVE_ITEM_FROM_CART_SUCCESS:"REMOVE_ITEM_FROM_CART_SUCCESS",
    REMOVE_ITEM_FROM_CART_FAIL:"REMOVE_ITEM_FROM_CART_FAIL"

}

export default CartTypes;

