export const productListType={
    FETCH_ALL_LATEST_PRODUCTS_START:"FETCH_ALL_LATEST_PRODUCTS_START",
    FETCH_ALL_LATEST_PRODUCTS_SUCCESS:"FETCH_ALL_LATEST_PRODUCTS_SUCCESS",
    FETCH_ALL_LATEST_PRODUCTS_FAIL:"FETCH_ALL_LATEST_PRODUCTS_FAIL"
}