const ProductDetailType={
    PRODUCT_DETAIL_FETCH_START:"PRODUCT_DETAIL_FETCH_START",
    PRODUCT_DETAIL_FETCH_SUCCESS:"PRODUCT_DETAIL_FETCH_SUCCESS",
    PRODUCT_DETAL_FETCH_FAILED:"PRODUCT_DETAL_FETCH_FAILED",
}
export default ProductDetailType;